/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netbanking;

/**
 *
 * @author joy
 */
public class AccountCreat extends javax.swing.JFrame {

    /**
     * Creates new form AccountCreat
     */
    public AccountCreat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        HeadingText = new javax.swing.JLabel();
        MenuePanel = new javax.swing.JPanel();
        HomePanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        HomeArrow = new javax.swing.JLabel();
        HomeArrow1 = new javax.swing.JLabel();
        TransferPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        TransferArrow = new javax.swing.JLabel();
        TransferArrow1 = new javax.swing.JLabel();
        AccountPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        AccountsArrow = new javax.swing.JLabel();
        AccountsArrow1 = new javax.swing.JLabel();
        CardsPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        CardsArrow = new javax.swing.JLabel();
        CardsArrow1 = new javax.swing.JLabel();
        ProfilePanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        ProfileArrow = new javax.swing.JLabel();
        ProfileArrow1 = new javax.swing.JLabel();
        LogOutPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        HomeSection = new javax.swing.JPanel();
        NamePlate = new javax.swing.JLabel();
        BalancePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        HomeAcNumber = new javax.swing.JLabel();
        BalanceLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CreditCardPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        CreditCardNumber = new javax.swing.JLabel();
        CreditCardBalance = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        TransactionPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TransactionTableHome = new javax.swing.JTable();
        ShopPanel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));

        HeadingText.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        HeadingText.setForeground(new java.awt.Color(255, 255, 255));
        HeadingText.setText("Home Section");

        MenuePanel.setBackground(new java.awt.Color(0, 0, 255));

        HomePanel.setBackground(new java.awt.Color(0, 0, 255));
        HomePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomePanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomePanelPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomePanelPanelMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon("F:\\All CSE File\\2nd Year 2nd Semester\\Project\\Net Banking\\Net-Banking-Software-main\\project2\\src\\project2\\Images\\icons8-home-30.png")); // NOI18N
        jLabel8.setText("Home");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel8.setIconTextGap(10);
        jLabel8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        HomeArrow1.setIcon(new javax.swing.ImageIcon("F:\\All CSE File\\2nd Year 2nd Semester\\Project\\Net Banking\\Net-Banking-Software-main\\project2\\src\\project2\\Images\\icons8-arrow-30.png")); // NOI18N

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HomeArrow1)
                .addGap(2, 2, 2)
                .addComponent(HomeArrow)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addGroup(HomePanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HomeArrow1)
                            .addComponent(HomeArrow))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        TransferPanel.setBackground(new java.awt.Color(0, 0, 255));
        TransferPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TransferPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TransferPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TransferPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TransferPanelMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon("F:\\All CSE File\\2nd Year 2nd Semester\\Project\\Net Banking\\Net-Banking-Software-main\\project2\\src\\project2\\Images\\icons8-data-transfer-30 (2).png")); // NOI18N
        jLabel9.setText("Transfer ");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel9.setIconTextGap(10);
        jLabel9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        TransferArrow1.setIcon(new javax.swing.ImageIcon("F:\\All CSE File\\2nd Year 2nd Semester\\Project\\Net Banking\\Net-Banking-Software-main\\project2\\src\\project2\\Images\\icons8-arrow-30.png")); // NOI18N

        javax.swing.GroupLayout TransferPanelLayout = new javax.swing.GroupLayout(TransferPanel);
        TransferPanel.setLayout(TransferPanelLayout);
        TransferPanelLayout.setHorizontalGroup(
            TransferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransferPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TransferArrow1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TransferArrow)
                .addContainerGap())
        );
        TransferPanelLayout.setVerticalGroup(
            TransferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransferPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TransferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addGroup(TransferPanelLayout.createSequentialGroup()
                        .addGroup(TransferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TransferArrow1)
                            .addComponent(TransferArrow))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        AccountPanel.setBackground(new java.awt.Color(0, 0, 255));
        AccountPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AccountPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AccountPanelPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AccountPanelPanelMouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon("F:\\All CSE File\\2nd Year 2nd Semester\\Project\\Net Banking\\Net-Banking-Software-main\\project2\\src\\project2\\Images\\icons8-money-bag-rupee-30 (2).png")); // NOI18N
        jLabel10.setText("Account");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel10.setIconTextGap(10);
        jLabel10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        AccountsArrow1.setIcon(new javax.swing.ImageIcon("F:\\All CSE File\\2nd Year 2nd Semester\\Project\\Net Banking\\Net-Banking-Software-main\\project2\\src\\project2\\Images\\icons8-arrow-30.png")); // NOI18N

        javax.swing.GroupLayout AccountPanelLayout = new javax.swing.GroupLayout(AccountPanel);
        AccountPanel.setLayout(AccountPanelLayout);
        AccountPanelLayout.setHorizontalGroup(
            AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AccountPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AccountsArrow))
                    .addGroup(AccountPanelLayout.createSequentialGroup()
                        .addComponent(AccountsArrow1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        AccountPanelLayout.setVerticalGroup(
            AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AccountPanelLayout.createSequentialGroup()
                        .addComponent(AccountsArrow)
                        .addGap(11, 11, 11)
                        .addComponent(AccountsArrow1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                .addContainerGap())
        );

        CardsPanel.setBackground(new java.awt.Color(0, 0, 255));
        CardsPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CardsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CardsPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CardsPanelPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CardsPanelPanelMouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon("F:\\All CSE File\\2nd Year 2nd Semester\\Project\\Net Banking\\Net-Banking-Software-main\\project2\\src\\project2\\Images\\icons8-mastercard-credit-card-30.png")); // NOI18N
        jLabel11.setText("Cards");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel11.setIconTextGap(10);
        jLabel11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        CardsArrow1.setIcon(new javax.swing.ImageIcon("F:\\All CSE File\\2nd Year 2nd Semester\\Project\\Net Banking\\Net-Banking-Software-main\\project2\\src\\project2\\Images\\icons8-arrow-30.png")); // NOI18N

        javax.swing.GroupLayout CardsPanelLayout = new javax.swing.GroupLayout(CardsPanel);
        CardsPanel.setLayout(CardsPanelLayout);
        CardsPanelLayout.setHorizontalGroup(
            CardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardsPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CardsArrow1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CardsArrow)
                .addContainerGap())
        );
        CardsPanelLayout.setVerticalGroup(
            CardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addGroup(CardsPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(CardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CardsArrow1)
                            .addComponent(CardsArrow))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        ProfilePanel.setBackground(new java.awt.Color(0, 0, 255));
        ProfilePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ProfilePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfilePanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProfilePanelPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProfilePanelPanelMouseExited(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon("F:\\All CSE File\\2nd Year 2nd Semester\\Project\\Net Banking\\Net-Banking-Software-main\\project2\\src\\project2\\Images\\icons8-male-user-30.png")); // NOI18N
        jLabel12.setText("Profile");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel12.setIconTextGap(10);
        jLabel12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        ProfileArrow1.setIcon(new javax.swing.ImageIcon("F:\\All CSE File\\2nd Year 2nd Semester\\Project\\Net Banking\\Net-Banking-Software-main\\project2\\src\\project2\\Images\\icons8-arrow-30.png")); // NOI18N

        javax.swing.GroupLayout ProfilePanelLayout = new javax.swing.GroupLayout(ProfilePanel);
        ProfilePanel.setLayout(ProfilePanelLayout);
        ProfilePanelLayout.setHorizontalGroup(
            ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfilePanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ProfileArrow1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProfileArrow))
        );
        ProfilePanelLayout.setVerticalGroup(
            ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ProfilePanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProfileArrow1)
                            .addComponent(ProfileArrow))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        LogOutPanel.setBackground(new java.awt.Color(0, 0, 255));
        LogOutPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogOutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogOutPanelPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogOutPanelPanelMouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon("F:\\All CSE File\\2nd Year 2nd Semester\\Project\\Net Banking\\Net-Banking-Software-main\\project2\\src\\project2\\Images\\icons8-logout-rounded-left-30.png")); // NOI18N
        jLabel13.setText("Log Out");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel13.setIconTextGap(10);
        jLabel13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout LogOutPanelLayout = new javax.swing.GroupLayout(LogOutPanel);
        LogOutPanel.setLayout(LogOutPanelLayout);
        LogOutPanelLayout.setHorizontalGroup(
            LogOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogOutPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LogOutPanelLayout.setVerticalGroup(
            LogOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogOutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout MenuePanelLayout = new javax.swing.GroupLayout(MenuePanel);
        MenuePanel.setLayout(MenuePanelLayout);
        MenuePanelLayout.setHorizontalGroup(
            MenuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TransferPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AccountPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CardsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ProfilePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LogOutPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MenuePanelLayout.setVerticalGroup(
            MenuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuePanelLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(HomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TransferPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AccountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CardsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProfilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogOutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        HomeSection.setBackground(new java.awt.Color(255, 255, 255));

        NamePlate.setFont(new java.awt.Font("Noto Sans JP", 0, 24)); // NOI18N
        NamePlate.setForeground(new java.awt.Color(31, 132, 255));
        NamePlate.setText("Hello, NameHere!");

        BalancePanel.setBackground(new java.awt.Color(56, 35, 234));
        BalancePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Available Balance");
        BalancePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Account #");
        BalancePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 47, -1, -1));

        HomeAcNumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        HomeAcNumber.setForeground(new java.awt.Color(255, 255, 255));
        HomeAcNumber.setText("123456789012");
        BalancePanel.add(HomeAcNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 47, -1, -1));

        BalanceLabel.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        BalanceLabel.setForeground(new java.awt.Color(255, 255, 255));
        BalanceLabel.setText(" 100000");
        BalancePanel.add(BalanceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 160, 50));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Online Bank");
        BalancePanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("F:\\All CSE File\\2nd Year 2nd Semester\\Project\\Net Banking\\Net-Banking-Software-main\\project2\\src\\project2\\Images\\image.png")); // NOI18N
        BalancePanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 170));

        jLabel5.setFont(new java.awt.Font("Noto Sans JP", 2, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Welcome to Online Bank");

        CreditCardPanel.setBackground(new java.awt.Color(56, 35, 234));
        CreditCardPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Credit Card Balance");
        CreditCardPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("XXXXXXXXXXXX");
        CreditCardPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        CreditCardNumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        CreditCardNumber.setForeground(new java.awt.Color(255, 255, 255));
        CreditCardNumber.setText("123");
        CreditCardPanel.add(CreditCardNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        CreditCardBalance.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        CreditCardBalance.setForeground(new java.awt.Color(255, 255, 255));
        CreditCardBalance.setText(" 100000");
        CreditCardPanel.add(CreditCardBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 160, 50));

        jLabel7.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        CreditCardPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon("F:\\All CSE File\\2nd Year 2nd Semester\\Project\\Net Banking\\Net-Banking-Software-main\\project2\\src\\project2\\Images\\gradient (4).png")); // NOI18N
        CreditCardPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 170));

        TransactionPanel.setBackground(new java.awt.Color(255, 255, 255));
        TransactionPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(205, 205, 205), new java.awt.Color(205, 205, 205)));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(16, 156, 202));
        jLabel14.setText("All Last Transaction");

        TransactionTableHome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TransactionTableHome.setForeground(new java.awt.Color(0, 0, 255));
        TransactionTableHome.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Account Number", "Amount", "C/D"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TransactionTableHome.setGridColor(new java.awt.Color(220, 220, 220));
        TransactionTableHome.setRowHeight(25);
        TransactionTableHome.setShowVerticalLines(false);
        TransactionTableHome.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TransactionTableHome);

        javax.swing.GroupLayout TransactionPanelLayout = new javax.swing.GroupLayout(TransactionPanel);
        TransactionPanel.setLayout(TransactionPanelLayout);
        TransactionPanelLayout.setHorizontalGroup(
            TransactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransactionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TransactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                    .addGroup(TransactionPanelLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        TransactionPanelLayout.setVerticalGroup(
            TransactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransactionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addContainerGap())
        );

        ShopPanel.setBackground(new java.awt.Color(0, 204, 255));
        ShopPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        ShopPanel.setMinimumSize(new java.awt.Dimension(367, 191));
        ShopPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Shop With Us");
        ShopPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, -1));

        jLabel20.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Buy Products From Our Store And Get  ");
        ShopPanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel21.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Cashback  upto Taka 1000");
        ShopPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        ShopPanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 80, 80));

        jLabel23.setFont(new java.awt.Font("Gulim", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Online Cart");
        ShopPanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 110, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon("F:\\All CSE File\\2nd Year 2nd Semester\\Project\\Net Banking\\Net-Banking-Software-main\\project2\\src\\project2\\Images\\pinkblue1.png")); // NOI18N
        ShopPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 210));

        javax.swing.GroupLayout HomeSectionLayout = new javax.swing.GroupLayout(HomeSection);
        HomeSection.setLayout(HomeSectionLayout);
        HomeSectionLayout.setHorizontalGroup(
            HomeSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeSectionLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(HomeSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CreditCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NamePlate, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(BalancePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(HomeSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TransactionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        HomeSectionLayout.setVerticalGroup(
            HomeSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeSectionLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(HomeSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomeSectionLayout.createSequentialGroup()
                        .addComponent(NamePlate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(44, 44, 44)
                        .addComponent(BalancePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(CreditCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HomeSectionLayout.createSequentialGroup()
                        .addComponent(TransactionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(ShopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(MenuePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(366, 366, 366)
                .addComponent(HeadingText)
                .addContainerGap(460, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 111, Short.MAX_VALUE)
                    .addComponent(HomeSection, javax.swing.GroupLayout.PREFERRED_SIZE, 968, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MenuePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(HeadingText)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(104, Short.MAX_VALUE)
                    .addComponent(HomeSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomePanelMouseClicked
        if(evt.getSource()==HomePanel){

            HomeSection.setVisible(true);
            TransferSection.setVisible(false);
            AccountsSection.setVisible(false);
            CardsSection.setVisible(false);
            ProfileSection.setVisible(false);
            HeadingText.setText("Home Section");
            HomeSectionMethod();
            HomeArrow.setVisible(true);
            TransferArrow.setVisible(false);
            AccountsArrow.setVisible(false);
            CardsArrow.setVisible(false);
            ProfileArrow.setVisible(false);
            transactionHistory();
        }
    }//GEN-LAST:event_HomePanelMouseClicked

    private void HomePanelPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomePanelPanelMouseEntered
        if(evt.getSource()==HomePanel){
            HomePanel.setBackground( new Color(9, 50, 236));
        }
    }//GEN-LAST:event_HomePanelPanelMouseEntered

    private void HomePanelPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomePanelPanelMouseExited
        if(evt.getSource()==HomePanel){
            HomePanel.setBackground( new Color(0, 0, 225));
        }
    }//GEN-LAST:event_HomePanelPanelMouseExited

    private void TransferPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransferPanelMouseClicked
        if(TransferPanel==evt.getSource()){

            HomeSection.setVisible(false);
            TransferSection.setVisible(true);
            AccountsSection.setVisible(false);
            CardsSection.setVisible(false);
            ProfileSection.setVisible(false);
            HeadingText.setText("Transfer Money");

            HomeArrow.setVisible(false);
            TransferArrow.setVisible(true);
            AccountsArrow.setVisible(false);
            CardsArrow.setVisible(false);
            ProfileArrow.setVisible(false);
            transactionHistory();
        }
    }//GEN-LAST:event_TransferPanelMouseClicked

    private void TransferPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransferPanelMouseEntered
        if(evt.getSource()==TransferPanel){
            TransferPanel.setBackground( new Color(9, 50, 236));
        }
    }//GEN-LAST:event_TransferPanelMouseEntered

    private void TransferPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransferPanelMouseExited
        if(evt.getSource()==TransferPanel){
            TransferPanel.setBackground( new Color(0, 0, 225));
        }
    }//GEN-LAST:event_TransferPanelMouseExited

    private void AccountPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountPanelMouseClicked
        if(evt.getSource()==AccountPanel){

            HomeSection.setVisible(false);
            TransferSection.setVisible(false);
            AccountsSection.setVisible(true);
            CardsSection.setVisible(false);
            ProfileSection.setVisible(false);
            HeadingText.setText("My Account");

            HomeArrow.setVisible(false);
            TransferArrow.setVisible(false);
            AccountsArrow.setVisible(true);
            CardsArrow.setVisible(false);
            ProfileArrow.setVisible(false);

            AccountsSectionMethod();
        }
    }//GEN-LAST:event_AccountPanelMouseClicked

    private void AccountPanelPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountPanelPanelMouseEntered
        if(evt.getSource()==AccountPanel){
            AccountPanel.setBackground( new Color(9, 50, 236));
        }
    }//GEN-LAST:event_AccountPanelPanelMouseEntered

    private void AccountPanelPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountPanelPanelMouseExited
        if(evt.getSource()==AccountPanel){
            AccountPanel.setBackground( new Color(0, 0, 225));
        }
    }//GEN-LAST:event_AccountPanelPanelMouseExited

    private void CardsPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CardsPanelMouseClicked
        if(evt.getSource()==CardsPanel){

            HomeSection.setVisible(false);
            TransferSection.setVisible(false);
            AccountsSection.setVisible(false);
            CardsSection.setVisible(true);
            ProfileSection.setVisible(false);
            HeadingText.setText("Cards Detail");

            HomeArrow.setVisible(false);
            TransferArrow.setVisible(false);
            AccountsArrow.setVisible(false);
            CardsArrow.setVisible(true);
            ProfileArrow.setVisible(false);

            CardsSectionMethod();
        }
    }//GEN-LAST:event_CardsPanelMouseClicked

    private void CardsPanelPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CardsPanelPanelMouseEntered
        if(evt.getSource()==CardsPanel){
            CardsPanel.setBackground( new Color(9, 50, 236));
        }
    }//GEN-LAST:event_CardsPanelPanelMouseEntered

    private void CardsPanelPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CardsPanelPanelMouseExited
        if(evt.getSource()==CardsPanel){
            CardsPanel.setBackground( new Color(0, 0, 225));
        }
    }//GEN-LAST:event_CardsPanelPanelMouseExited

    private void ProfilePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfilePanelMouseClicked
        if(evt.getSource()==ProfilePanel){

            HomeSection.setVisible(false);
            TransferSection.setVisible(false);
            AccountsSection.setVisible(false);
            CardsSection.setVisible(false);
            ProfileSection.setVisible(true);
            HeadingText.setText("My Profile");

            HomeArrow.setVisible(false);
            TransferArrow.setVisible(false);
            AccountsArrow.setVisible(false);
            CardsArrow.setVisible(false);
            ProfileArrow.setVisible(true);
            ProfileSection();
        }
    }//GEN-LAST:event_ProfilePanelMouseClicked

    private void ProfilePanelPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfilePanelPanelMouseEntered
        if(evt.getSource()==ProfilePanel){
            ProfilePanel.setBackground( new Color(9, 50, 236));
        }
    }//GEN-LAST:event_ProfilePanelPanelMouseEntered

    private void ProfilePanelPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfilePanelPanelMouseExited
        if(evt.getSource()==ProfilePanel){
            ProfilePanel.setBackground( new Color(0, 0, 225));
        }
    }//GEN-LAST:event_ProfilePanelPanelMouseExited

    private void LogOutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutPanelMouseClicked
        setVisible(false);
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_LogOutPanelMouseClicked

    private void LogOutPanelPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutPanelPanelMouseEntered
        if(evt.getSource()==LogOutPanel){
            LogOutPanel.setBackground( new Color(9, 50, 236));
        }
    }//GEN-LAST:event_LogOutPanelPanelMouseEntered

    private void LogOutPanelPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutPanelPanelMouseExited
        if(evt.getSource()==LogOutPanel){
            LogOutPanel.setBackground( new Color(0, 0, 225));
        }
    }//GEN-LAST:event_LogOutPanelPanelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountCreat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountCreat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountCreat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountCreat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountCreat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccountPanel;
    private javax.swing.JLabel AccountsArrow;
    private javax.swing.JLabel AccountsArrow1;
    private javax.swing.JLabel BalanceLabel;
    private javax.swing.JPanel BalancePanel;
    private javax.swing.JLabel CardsArrow;
    private javax.swing.JLabel CardsArrow1;
    private javax.swing.JPanel CardsPanel;
    private javax.swing.JLabel CreditCardBalance;
    private javax.swing.JLabel CreditCardNumber;
    private javax.swing.JPanel CreditCardPanel;
    private javax.swing.JLabel HeadingText;
    private javax.swing.JLabel HomeAcNumber;
    private javax.swing.JLabel HomeArrow;
    private javax.swing.JLabel HomeArrow1;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JPanel HomeSection;
    private javax.swing.JPanel LogOutPanel;
    private javax.swing.JPanel MenuePanel;
    private javax.swing.JLabel NamePlate;
    private javax.swing.JLabel ProfileArrow;
    private javax.swing.JLabel ProfileArrow1;
    private javax.swing.JPanel ProfilePanel;
    private javax.swing.JPanel ShopPanel;
    private javax.swing.JPanel TransactionPanel;
    private javax.swing.JTable TransactionTableHome;
    private javax.swing.JLabel TransferArrow;
    private javax.swing.JLabel TransferArrow1;
    private javax.swing.JPanel TransferPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
